plugins {
    id 'java-library'
    id 'maven-publish'
}

repositories {
    mavenCentral()
}

dependencies {
    compileOnly 'com.google.code.findbugs:jsr305:3.0.2'
    testImplementation 'junit:junit:4.13.2'
}

group = 'com.mod-buildcraft'
version = rootProject.version
base { archivesName = 'buildcraft-libexpression' }

java {
    toolchain.languageVersion = JavaLanguageVersion.of(21)
    withSourcesJar()
}

sourceSets {
    main {
        java {
            srcDir 'src/main/java'
            srcDir 'src/autogen/java'
        }
    }
    test {
        java { srcDir 'src/test/java' }
    }
    generator {
        java { srcDir 'src/generator/java' }
        resources { srcDir 'src/generator/resources' }
    }
}

task removeOldAutoGen {
    doLast {
        delete 'src/autogen/java/buildcraft'
    }
}

task generateSources(type: JavaExec, dependsOn: removeOldAutoGen) {
    classpath = sourceSets.generator.runtimeClasspath
    mainClass = 'buildcraft.meta.generate.AutoGenerator'
    args '-out', 'src/autogen/java', '-run', '-quiet'
}

compileJava.dependsOn generateSources

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url rootProject.layout.buildDirectory.dir('repo')
        }
    }
}
